language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
    - GTEST_COLOR=1

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
  - ../ci/before_script.sh

script:
  - make
  - make test

after_success:
  - ../ci/after_success.sh
