language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
    - GTEST_COLOR=1

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
